name: goalkeeper
description: A simple Flutter app to help you achieve your goals!

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dynamic_theme: ^1.0.1
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter:
  uses-material-design: true
  assets:
      - img/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "img/icon.png"