name: goalkeeper
description: A simple Flutter app to help you achieve your goals!

version: 1.3+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1
  eva_icons_flutter: ^2.0.0
  flutter_local_notifications: ^1.1.2
  flutter_speed_dial: ^1.2.5
  path_provider: ^1.5.1
  sqflite: ^1.1.8
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  mockito: ^4.1.0

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  adaptive_icon_background: '#fafafa'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true
  assets:
      - assets/credits/
      - assets/icon/